### ISSUE TITLE
How can I use my groq API

### ISSUE THREAD

**Issue by zizeyan** [browser-use/browser-use#54]
Dear sir：
Please help me,this is my code:

import getpass
import os
from langchain_groq import ChatGroq
from langchain_openai import ChatOpenAI
from browser_use import Agent
import asyncio

async def main():
    agent = Agent(
        task="Find a one-way flight from Bali to Oman on 12 January 2025 on Google Flights. Return me the cheapest option.",
        llm=ChatGroq(
            
            model="llama-3.1-70b-versatile",
            temperature=0,
            max_tokens=None,
            timeout=None,
            max_retries=2,
            
    # other params...
            ),
    )
    result = await agent.run()
    print(result)
    
if __name__ == "__main__":
    
    asyncio.run(main())
    
    
Here is the error message I encountered:
INFO     [root] Anonymized telemetry enabled. See https://github.com/gregpr07/browser-use for more information.
INFO     [agent] 🚀 Starting task: Find a one-way flight from Bali to Oman on 12 January 2025 on Google Flights. Return me the cheapest option.
INFO     [agent]
📍 Step 1
ERROR    [agent] ❌ Result failed 1/5 times:
 Unexpected error: Error code: 400 - {'error': {'message': 'message[2].content must be a string', 'type': 'invalid_request_error'}}
Stacktrace:
Traceback (most recent call last):
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 123, in step
    model_output = await self.get_next_action(state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\utils.py", line 36, in wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 188, in get_next_action
    response: dict[str, Any] = await structured_llm.ainvoke(input_messages)  # type: ignore
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3066, in ainvoke
    input = await asyncio.create_task(part(), context=context)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3773, in ainvoke
    results = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3763, in _ainvoke_step
    return await asyncio.create_task(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 5366, in ainvoke
    return await self.bound.ainvoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 307, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 796, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 756, in agenerate
    raise exceptions[0]
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 924, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_groq\chat_models.py", line 495, in _agenerate
    response = await self.async_client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\resources\chat\completions.py", line 598, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1808, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1516, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1617, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.BadRequestError: Error code: 400 - {'error': {'message': 'message[2].content must be a string', 'type': 'invalid_request_error'}}

INFO     [agent]
📍 Step 1
ERROR    [agent] ❌ Result failed 2/5 times:
 Unexpected error: Error code: 400 - {'error': {'message': 'message[3].content must be a string', 'type': 'invalid_request_error'}}
Stacktrace:
Traceback (most recent call last):
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 123, in step
    model_output = await self.get_next_action(state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\utils.py", line 36, in wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 188, in get_next_action
    response: dict[str, Any] = await structured_llm.ainvoke(input_messages)  # type: ignore
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3066, in ainvoke
    input = await asyncio.create_task(part(), context=context)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3773, in ainvoke
    results = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3763, in _ainvoke_step
    return await asyncio.create_task(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 5366, in ainvoke
    return await self.bound.ainvoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 307, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 796, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 756, in agenerate
    raise exceptions[0]
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 924, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_groq\chat_models.py", line 495, in _agenerate
    response = await self.async_client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\resources\chat\completions.py", line 598, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1808, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1516, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1617, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.BadRequestError: Error code: 400 - {'error': {'message': 'message[3].content must be a string', 'type': 'invalid_request_error'}}

INFO     [agent]
📍 Step 1
ERROR    [agent] ❌ Result failed 3/5 times:
 Unexpected error: Error code: 400 - {'error': {'message': 'message[4].content must be a string', 'type': 'invalid_request_error'}}
Stacktrace:
Traceback (most recent call last):
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 123, in step
    model_output = await self.get_next_action(state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\utils.py", line 36, in wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 188, in get_next_action
    response: dict[str, Any] = await structured_llm.ainvoke(input_messages)  # type: ignore
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3066, in ainvoke
    input = await asyncio.create_task(part(), context=context)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3773, in ainvoke
    results = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3763, in _ainvoke_step
    return await asyncio.create_task(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 5366, in ainvoke
    return await self.bound.ainvoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 307, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 796, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 756, in agenerate
    raise exceptions[0]
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 924, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_groq\chat_models.py", line 495, in _agenerate
    response = await self.async_client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\resources\chat\completions.py", line 598, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1808, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1516, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1617, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.BadRequestError: Error code: 400 - {'error': {'message': 'message[4].content must be a string', 'type': 'invalid_request_error'}}

INFO     [agent]
📍 Step 1
ERROR    [agent] ❌ Result failed 4/5 times:
 Unexpected error: Error code: 400 - {'error': {'message': 'message[5].content must be a string', 'type': 'invalid_request_error'}}
Stacktrace:
Traceback (most recent call last):
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 123, in step
    model_output = await self.get_next_action(state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\utils.py", line 36, in wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 188, in get_next_action
    response: dict[str, Any] = await structured_llm.ainvoke(input_messages)  # type: ignore
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3066, in ainvoke
    input = await asyncio.create_task(part(), context=context)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3773, in ainvoke
    results = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3763, in _ainvoke_step
    return await asyncio.create_task(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 5366, in ainvoke
    return await self.bound.ainvoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 307, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 796, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 756, in agenerate
    raise exceptions[0]
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 924, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_groq\chat_models.py", line 495, in _agenerate
    response = await self.async_client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\resources\chat\completions.py", line 598, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1808, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1516, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1617, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.BadRequestError: Error code: 400 - {'error': {'message': 'message[5].content must be a string', 'type': 'invalid_request_error'}}

INFO     [agent]
📍 Step 1
ERROR    [agent] ❌ Result failed 5/5 times:
 Unexpected error: Error code: 400 - {'error': {'message': 'message[6].content must be a string', 'type': 'invalid_request_error'}}
Stacktrace:
Traceback (most recent call last):
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 123, in step
    model_output = await self.get_next_action(state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\utils.py", line 36, in wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\browser_use\agent\service.py", line 188, in get_next_action
    response: dict[str, Any] = await structured_llm.ainvoke(input_messages)  # type: ignore
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3066, in ainvoke
    input = await asyncio.create_task(part(), context=context)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3773, in ainvoke
    results = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 3763, in _ainvoke_step
    return await asyncio.create_task(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\runnables\base.py", line 5366, in ainvoke
    return await self.bound.ainvoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 307, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 796, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 756, in agenerate
    raise exceptions[0]
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py", line 924, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\langchain_groq\chat_models.py", line 495, in _agenerate
    response = await self.async_client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\resources\chat\completions.py", line 598, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1808, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1516, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bay\anaconda3\Lib\site-packages\groq\_base_client.py", line 1617, in _request
    raise self._make_status_error_from_response(err.response) from None
groq.BadRequestError: Error code: 400 - {'error': {'message': 'message[6].content must be a string', 'type': 'invalid_request_error'}}

ERROR    [agent] ❌ Stopping due to 5 consecutive failures
Press Enter to close Browser...

**Comment by sam26880** [comment]
I'm getting the same error when trying to use Groq API.

The issue is likely within the browser_use library's code where it formats the prompt for the LLM. It's probably constructing a message where the content field is accidentally set to a non-string value, such as a list, dictionary, or None.

But I haven't been able to find where exactly. There are no detailed stack traces

**Comment by flavionc** [comment]
The same here. Waiting for someone else to help.

**Comment by Xlt3h** [comment]
has anyone got any solution?

**Comment by moodpanda** [comment]
i tried changing the system prompt to user message prompt it suddenly work but sometimes it raise the "message limit size exception"

**Comment by moodpanda** [comment]
![Image](https://github.com/user-attachments/assets/cf9f77fd-8568-4de4-8c48-42c74848fcc6)

**Comment by goldenjayr** [comment]
``	llm=ChatOpenAI(
			base_url='https://api.groq.com/openai/v1',
			model='llama-3.3-70b-versatile',
			api_key=SecretStr(api_key),
		),

i use this

**Comment by ChirawatCh** [comment]
> ` llm=ChatOpenAI( base_url='https://api.groq.com/openai/v1', model='llama-3.3-70b-versatile', api_key=SecretStr(api_key), ),`
> 
> i use this

It does not work.

**Comment by Cfomodz** [comment]
Thank you for opening this issue and sharing your code and error details!

It looks like the integration path you're using (`langchain_groq.ChatGroq`) is not the one shown in our current documentation or examples. We recommend using the `langchain_openai.ChatOpenAI` class with the appropriate `base_url`, `model`, and `api_key` for Groq/X AI. You can find example code and setup instructions here:

[Supported Models - X AI section](https://github.com/browser-use/browser-use/blob/main/docs/customize/supported-models.mdx#L255-L288)
[Quickstart Guide](https://github.com/browser-use/browser-use/blob/main/docs/quickstart.mdx#L41-L65)
[Example Groq integration](https://github.com/browser-use/browser-use/blob/main/examples/models/grok.py)

If your use case requires something not covered by these examples, or if you believe this issue was closed in error, we apologize and encourage you to follow up or reopen with more details. We're happy to help!

Thanks again for contributing to Browser-Use!

**Comment by AlexandruRoman** [comment]
@Cfomodz Don't confuse Groq with Grok. It would be amazing to have a Groq integration

**Comment by MagMueller** [comment]
https://github.com/browser-use/browser-use/blob/main/examples/models/llama4-groq.py
