### ISSUE TITLE
ValueError: I/O operation on closed pipe

### ISSUE THREAD

**Issue by Aleshanmaistry** [browser-use/browser-use#73]
Getting the below error after running the following code

from langchain_openai import ChatOpenAI
from browser_use import Agent
import asyncio

async def main():
    agent = Agent(
        task="Find a one-way flight from Bali to Oman on 12 January 2025 on Google Flights. Return me the cheapest option.",
        llm=ChatOpenAI(model="gpt-4o",api_key=OPENAI_API_KEY),
    )
    result = await agent.run()
    print(result)

if __name__ == "__main__":
    asyncio.run(main())

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DD17CCE480>
Traceback (most recent call last):
  File "C:\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001DD17CCCC20>
Traceback (most recent call last):
  File "C:\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

Setup:
Running in anaconda
browser-use                   0.1.15
asyncio                           3.4.3
langchain-openai           0.2.10

**Comment by gregpr07** [comment]
Which Python version are you running?

**Comment by Aleshanmaistry** [comment]
3.11.10 | packaged by Anaconda, Inc. | (main, Oct  3 2024, 07:22:26) [MSC v.1929 64 bit (AMD64)]

**Comment by aiwenForGit** [comment]
I have same problem.
so help me .

**Comment by gl81567405** [comment]
I have same problem.
so help me .

**Comment by Cfomodz** [comment]
@aiwenForGit @gl81567405 Can you two please share your current system details: OS, Python Version, Anaconda?, browser-use version -- Thanks!

**Comment by Cfomodz** [comment]
Hi everyone,

As there has been no update after my request for additional information 3 weeks ago, and due to the fast-moving nature of the repo with new versions being released and several PRs being merged since the issue was opened, I am closing this issue.

I understand this may still be a problem. If it is, please reach out via the Discord server's support channel or raise another issue using the appropriate issue template.

Thank you!
