### ISSUE TITLE
ValueError: I/O operation on closed pipe

### ISSUE THREAD

**Issue by 729973389** [browser-use/browser-use#77]
This error occurs when the agent is closed after running. Why is this?

Exception ignored in: <function Browser.__del__ at 0x0000020A60DBA7A0>
Traceback (most recent call last):
  File "D:\project\browser_use\browser-use-main1\browser_use\browser\service.py", line 451, in __del__
    asyncio.run(self.close(force=True))
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\project\browser_use\browser-use-main1\browser_use\browser\service.py", line 445, in close
    await session.browser.close()
  File "C:\Users\72997\.conda\envs\browser_use\Lib\site-packages\playwright\async_api\_generated.py", line 14176, in close
    return mapping.from_maybe_impl(await self._impl_obj.close(reason=reason))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\site-packages\playwright\_impl\_browser.py", line 192, in close
    raise e
  File "C:\Users\72997\.conda\envs\browser_use\Lib\site-packages\playwright\_impl\_browser.py", line 189, in close
    await self._channel.send("close", {"reason": reason})
  File "C:\Users\72997\.conda\envs\browser_use\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
AttributeError: Browser.close: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020A5C1DD1C0>
Traceback (most recent call last):
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020A5C1DD1C0>
Traceback (most recent call last):
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000020A5C1BB9C0>
Traceback (most recent call last):
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                        ^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\72997\.conda\envs\browser_use\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

**Comment by gregpr07** [comment]
Will take a look!

**Comment by simonbm** [comment]
INFO     [agent] ✅ Task completed successfully
INFO     [agent] Created GIF at agent_history.gif
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000262271BF240>
Traceback (most recent call last):
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000262271BD9E0>
Traceback (most recent call last):
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000262271BF240>
Traceback (most recent call last):
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonbm\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

**Comment by Cfomodz** [comment]
We’ve reviewed the current release and are unable to reproduce the ValueError: I/O operation on closed pipe error described here. This issue was raised a while ago, and the agent and browser shutdown logic have since been improved. The current codebase handles resource cleanup and shutdown-related errors more gracefully.

**Comment by whoiscicada** [comment]
INFO     [Agent]   ▶️   done: text: The initial step of navigating to the eClinicalWorks portal URL (https://caazaf4wjqjeutsgm7app.ecwcloud.com/mobiledoc/jsp/webemmr/login/newLogin.jsp) f..., success: False
INFO     [Agent]
📄  Final Result:
The initial step of navigating to the eClinicalWorks portal URL (https://caazaf4wjqjeutsgm7app.ecwcloud.com/mobiledoc/jsp/webemr/login/newLogin.jsp) failed repeatedly due to a 'Session with given id not found' error. As a result, the task to log in, navigate to the new patient form, and fill in dummy details could not be started.


INFO     [Agent] 
INFO     [Agent] Did the Agent not work as expected? Let us fix this!
INFO     [Agent]    Open a short issue on GitHub: https://github.com/browser-use/browser-use/issues
INFO     [BrowserSession] [SessionManager] Cleared all session tracking
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E412628220>
Traceback (most recent call last):
  File "C:\Users\whois\AppData\Roaming\uv\python\cpython-3.12.12-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\whois\AppData\Roaming\uv\python\cpython-3.12.12-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whois\AppData\Roaming\uv\python\cpython-3.12.12-windows-x86_64-none\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E412628220>
Traceback (most recent call last):
  File "C:\Users\whois\AppData\Roaming\uv\python\cpython-3.12.12-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
                               ^^^^^^^^
  File "C:\Users\whois\AppData\Roaming\uv\python\cpython-3.12.12-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whois\AppData\Roaming\uv\python\cpython-3.12.12-windows-x86_64-none\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
(Browser use 1) PS C:\Users\whois\OneDrive\Desktop\Browser use 1>   facinf similar issue
